```yaml
service: nuxt-ssr-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  nuxt:
    handler: lambda/nuxt.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline
```